CREATE TABLE "Players" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username" character varying(100) NOT NULL,
    "ProfileUrl" character varying(300) NOT NULL,
    "RobloxUserId" bigint NOT NULL,
    "TotalPlaySeconds" bigint NOT NULL DEFAULT 0,
    "CurrentlyPlaying" character varying(200) NULL,
    "LastSeenPlaying" timestamp with time zone NULL,
    "AvatarUrl" character varying(700) NULL,
    "Club" character varying(100) NULL DEFAULT 'PIH',
    "DiscordUserId" character varying(100) NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL
);
CREATE UNIQUE INDEX "IX_Players_RobloxUserId" ON "Players" ("RobloxUserId");

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username" character varying(50) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" character varying(10) NOT NULL DEFAULT 'User',
    "CreatedAt" timestamp with time zone NOT NULL,
    "PlayerId" integer NULL,
    "DiscordUserId" character varying(100) NULL,
    "RobloxUsername" character varying(100) NULL,
    "RobloxUserId" bigint NULL
);
CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Players_PlayerId"
    FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE SET NULL;

INSERT INTO "Players" ("Username","ProfileUrl","RobloxUserId","TotalPlaySeconds","CreatedAt")
VALUES ('TestPlayer','https://roblox.com/users/1/profile',111111,3600, now());
