CREATE TABLE "DailyPlaytime" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PlayerId" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "PlaySeconds" bigint NOT NULL,
    CONSTRAINT "PK_DailyPlaytime" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DailyPlaytime_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX "IX_DailyPlaytime_PlayerId_Date" ON "DailyPlaytime" ("PlayerId", "Date");

CREATE TABLE "PlayerActivityEvents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PlayerId" integer NOT NULL,
    "EventType" character varying(40) NOT NULL,
    "Message" character varying(500) NOT NULL,
    "OccurredAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_PlayerActivityEvents_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE CASCADE
);

CREATE TABLE "VerificationCodes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RobloxUserId" bigint NOT NULL,
    "Code" character varying(32) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "UsedAt" timestamp with time zone NULL,
    "ClaimToken" character varying(64) NULL,
    "ClaimedAt" timestamp with time zone NULL
);
CREATE UNIQUE INDEX "IX_VerificationCodes_Code" ON "VerificationCodes" ("Code");

CREATE TABLE "JoinRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RobloxUsername" character varying(100) NOT NULL,
    "RobloxUserId" bigint NOT NULL,
    "DiscordUserId" character varying(100) NOT NULL,
    "Club" character varying(100) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "Note" character varying(500) NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReviewedAt" timestamp with time zone NULL,
    "ReviewedBy" character varying(50) NULL,
    "UserId" integer NULL,
    CONSTRAINT "FK_JoinRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);
