#!/usr/bin/env python3
"""Step 1: Create all tables in PostgreSQL."""
import psycopg2
import os

PG_CONN = os.environ.get(
    "DATABASE_URL",
    "host=ep-young-wave-aytqmhdg.c-5.us-east-2.aws.neon.tech "
    "port=5432 dbname=neondb user=neondb_owner "
    "password=npg_hdD0Ui2nxGPc sslmode=require sslrootcert=verify-full"
)

CREATE_TABLES = """
CREATE TABLE IF NOT EXISTS Players (
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR(100) NOT NULL,
    ProfileUrl VARCHAR(300) NOT NULL,
    RobloxUserId BIGINT NOT NULL,
    IsOnline BOOLEAN NOT NULL DEFAULT FALSE,
    CurrentlyPlaying VARCHAR(200),
    LastSeenPlaying TIMESTAMP,
    TotalPlaySeconds BIGINT NOT NULL DEFAULT 0,
    AvatarUrl VARCHAR(700),
    Club VARCHAR(100) NOT NULL DEFAULT 'PIH',
    CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
    UpdatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
    DiscordUserId VARCHAR(100)
);
CREATE UNIQUE INDEX IF NOT EXISTS IX_Players_RobloxUserId ON Players(RobloxUserId);

CREATE TABLE IF NOT EXISTS DailyPlaytime (
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PlayerId INTEGER NOT NULL REFERENCES Players(Id) ON DELETE CASCADE,
    Date DATE NOT NULL,
    PlaySeconds BIGINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS IX_DailyPlaytime_PlayerId_Date ON DailyPlaytime(PlayerId, Date);

CREATE TABLE IF NOT EXISTS PlayerActivityEvents (
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PlayerId INTEGER NOT NULL REFERENCES Players(Id) ON DELETE CASCADE,
    EventType VARCHAR(40) NOT NULL,
    Message VARCHAR(500) NOT NULL,
    OccurredAt TIMESTAMP NOT NULL,
    DeltaSeconds BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS IX_PlayerActivityEvents_PlayerId_OccurredAt ON PlayerActivityEvents(PlayerId, OccurredAt);

CREATE TABLE IF NOT EXISTS Users (
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR(50) NOT NULL,
    PasswordHash TEXT NOT NULL,
    Role VARCHAR(10) NOT NULL DEFAULT 'User',
    CreatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS IX_Users_Username ON Users(Username);

CREATE TABLE IF NOT EXISTS JoinRequests (
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RobloxUsername VARCHAR(100) NOT NULL,
    RobloxUserId BIGINT NOT NULL,
    DiscordUserId VARCHAR(100) NOT NULL DEFAULT '',
    Club VARCHAR(100) NOT NULL,
    Status VARCHAR(20) NOT NULL,
    Note VARCHAR(500),
    CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
    ReviewedAt TIMESTAMP,
    ReviewedBy VARCHAR(50)
);
CREATE INDEX IF NOT EXISTS IX_JoinRequests_RobloxUserId_Status ON JoinRequests(RobloxUserId, Status);
"""

def main():
    pg_db = psycopg2.connect(PG_CONN)
    pg_cur = pg_db.cursor()
    pg_cur.execute(CREATE_TABLES)
    pg_db.commit()
    print("✅ All tables created!")
    pg_db.close()

if __name__ == "__main__":
    main()
