// <auto-generated />
using System;
using ClubPlaytime.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubPlaytime.Api.Migrations
{
    [DbContext(typeof(ClubPlaytimeDbContext))]
    [Migration("20260710075428_AddClubToPlayer")]
    partial class AddClubToPlayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ClubPlaytime.Api.Models.DailyPlaytime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Date")
                        .IsUnique();

                    b.ToTable("DailyPlaytime", (string)null);
                });

            modelBuilder.Entity("ClubPlaytime.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(700)
                        .HasColumnType("TEXT");

                    b.Property<string>("Club")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("PIH");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentlyPlaying")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenPlaying")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("RobloxUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalPlaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RobloxUserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ClubPlaytime.Api.Models.PlayerActivityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DeltaSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "OccurredAt");

                    b.ToTable("PlayerActivityEvents");
                });

            modelBuilder.Entity("ClubPlaytime.Api.Models.DailyPlaytime", b =>
                {
                    b.HasOne("ClubPlaytime.Api.Models.Player", "Player")
                        .WithMany("DailyPlaytimes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ClubPlaytime.Api.Models.PlayerActivityEvent", b =>
                {
                    b.HasOne("ClubPlaytime.Api.Models.Player", "Player")
                        .WithMany("ActivityEvents")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ClubPlaytime.Api.Models.Player", b =>
                {
                    b.Navigation("ActivityEvents");

                    b.Navigation("DailyPlaytimes");
                });
#pragma warning restore 612, 618
        }
    }
}
